### ISSUE TITLE
Need help

### ISSUE THREAD

**Issue by stdusr** [merwane/oogway#1]
Good day,
would you mind providing a small example, how do I generate all possible BTC public addresses (P2PKH, P2SH, Bech32) using existing WIF private key, in string format?

**Comment by merwane** [comment]
Hey @stdusr, the library handles addresses generation via a mnemonic phrase (and optionally a passphrase), but cannot handle generation from WIF. I think you can use [bit by ofek](https://ofek.dev/bit/guide/keys.html) to generate from a WIF, although that would only handle P2PKH and P2SH.

If you want to generate from mnemonic phrases using [oogway](https://oogway.6conf.com/keys/reference.html#key), it would work with something like this:

```python
from oogway import Key

phrases = [...]
addresses = []

for phrase in phrases:
      key = Key(mnemonic=phrase)
      bech32 = key.address(_format="Bech32")
      p2pkh = key.address(_format="P2PKH")
      p2sh = key.address(_format="P2SH")
      
      addr = {
           "bech32": bech32,
           "p2pkh": p2pkh,
           "p2sh": p2sh
      }
      addresses.append(addr)

print(addresses)
```

If you absolutely need to generate from WIF, open an issue and I'll work on it when I can :)
