### ISSUE TITLE
Please use another bitcoin fees API provider

### ISSUE THREAD

**Issue by bretton** [merwane/oogway#2]
Hi, I'm not familiar with your project. I did a search for `https://bitcoinfees.earn.com/api/v1/fees/recommended` and am alerting projects using this API to inaccurate & old data.

An up-to-date API with accurate data would be `https://mempool.space/api/v1/fees/recommended` or some alternative.

https://github.com/merwane/oogway/blob/b5113486d980d76dda3ea7a78cad905175ee17e0/oogway/fees.py

**Comment by merwane** [comment]
Hi @bretton, you can also get the fees from the Blockstream API. Adding another provider is pretty easy as you just need to add the endpoint, you can submit a PR.
